import type { Product, Category } from '@/types/product.types';

export const staticCategories: Category[] = [
  {
    id: 'cat-living-room',
    name: 'Living Room',
    slug: 'living-room',
    description: 'Sofas, coffee tables, TV units and more',
    sortOrder: 1,
  },
  {
    id: 'cat-bedroom',
    name: 'Bedroom',
    slug: 'bedroom',
    description: 'Beds, wardrobes, dressers and nightstands',
    sortOrder: 2,
  },
  {
    id: 'cat-dining-room',
    name: 'Dining Room',
    slug: 'dining-room',
    description: 'Dining tables and chairs',
    sortOrder: 3,
  },
  {
    id: 'cat-home-office',
    name: 'Home Office',
    slug: 'home-office',
    description: 'Desks, chairs and storage',
    sortOrder: 4,
  },
  {
    id: 'cat-outdoor',
    name: 'Outdoor',
    slug: 'outdoor',
    description: 'Garden and patio furniture',
    sortOrder: 5,
  },
];

export const staticProducts: Product[] = [
  {
    id: 'p1',
    name: 'Palazzo Velvet Sofa',
    slug: 'palazzo-velvet-sofa',
    categoryId: 'cat-living-room',
    category: staticCategories[0],
    price: 185000,
    salePrice: 162000,
    material: 'Italian Velvet',
    stock: 8,
    isFeatured: true,
    isActive: true,
    tags: ['sofa', 'velvet', 'luxury'],
    description: 'Handcrafted 3-seater sofa upholstered in rich Italian velvet with solid teak wood frame.',
    images: [
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800',
      'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    name: 'Maharaja King Bed',
    slug: 'maharaja-king-bed',
    categoryId: 'cat-bedroom',
    category: staticCategories[1],
    price: 245000,
    material: 'Teak Wood',
    stock: 5,
    isFeatured: true,
    isActive: true,
    tags: ['bed', 'king', 'teak'],
    description: 'Majestic king-size bed with intricately carved teak headboard and premium slat base.',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    name: 'Elara Dining Table',
    slug: 'elara-dining-table',
    categoryId: 'cat-dining-room',
    category: staticCategories[2],
    price: 98000,
    salePrice: 89000,
    material: 'Marble & Steel',
    stock: 12,
    isFeatured: true,
    isActive: true,
    tags: ['dining', 'marble', 'modern'],
    description: '8-seater dining table with Italian marble top and powder-coated steel legs.',
    images: [
      'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=800',
      'https://images.unsplash.com/photo-1577140917170-285929fb55b7?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    name: 'Zenith Executive Desk',
    slug: 'zenith-executive-desk',
    categoryId: 'cat-home-office',
    category: staticCategories[3],
    price: 72000,
    material: 'Walnut Wood',
    stock: 10,
    isFeatured: false,
    isActive: true,
    tags: ['desk', 'office', 'walnut'],
    description: 'Premium walnut executive desk with integrated cable management and leather-inlay writing pad.',
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    name: 'Serenity Lounge Chair',
    slug: 'serenity-lounge-chair',
    categoryId: 'cat-living-room',
    category: staticCategories[0],
    price: 55000,
    salePrice: 48000,
    material: 'Leather',
    stock: 15,
    isFeatured: true,
    isActive: true,
    tags: ['chair', 'leather', 'lounge'],
    description: 'Mid-century modern lounge chair in full-grain Italian leather with walnut legs.',
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800',
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    name: 'Garden Orbit Set',
    slug: 'garden-orbit-set',
    categoryId: 'cat-outdoor',
    category: staticCategories[4],
    price: 68000,
    material: 'Teak & Rope',
    stock: 6,
    isFeatured: false,
    isActive: true,
    tags: ['outdoor', 'garden', 'teak'],
    description: '4-piece outdoor seating set in weather-resistant teak with hand-woven rope accents.',
    images: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p7',
    name: 'Aurora Wardrobe',
    slug: 'aurora-wardrobe',
    categoryId: 'cat-bedroom',
    category: staticCategories[1],
    price: 135000,
    salePrice: 118000,
    material: 'Engineered Wood',
    stock: 7,
    isFeatured: false,
    isActive: true,
    tags: ['wardrobe', 'storage', 'bedroom'],
    description: '6-door wardrobe with integrated LED lighting, velvet-lined drawers and mirrored panels.',
    images: [
      'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800',
      'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p8',
    name: 'Nomad Coffee Table',
    slug: 'nomad-coffee-table',
    categoryId: 'cat-living-room',
    category: staticCategories[0],
    price: 38000,
    salePrice: 32000,
    material: 'Mango Wood',
    stock: 20,
    isFeatured: false,
    isActive: true,
    tags: ['coffee table', 'mango wood', 'boho'],
    description: 'Organic-edged live-edge mango wood coffee table on hairpin legs.',
    images: [
      'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800',
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p9',
    name: 'Prestige Dining Chair',
    slug: 'prestige-dining-chair',
    categoryId: 'cat-dining-room',
    category: staticCategories[2],
    price: 18500,
    material: 'Beechwood & Fabric',
    stock: 40,
    isFeatured: false,
    isActive: true,
    tags: ['chair', 'dining', 'upholstered'],
    description: 'Ergonomic upholstered dining chair with solid beechwood frame — sold as a set of 2.',
    images: [
      'https://images.unsplash.com/photo-1503602642458-232111445657?w=800',
      'https://images.unsplash.com/photo-1506898667547-42e22a46e125?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p10',
    name: 'Nova Study Chair',
    slug: 'nova-study-chair',
    categoryId: 'cat-home-office',
    category: staticCategories[3],
    price: 28000,
    salePrice: 24000,
    material: 'Mesh & Steel',
    stock: 18,
    isFeatured: false,
    isActive: true,
    tags: ['chair', 'ergonomic', 'office'],
    description: 'High-back ergonomic mesh chair with lumbar support and adjustable armrests.',
    images: [
      'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=800',
      'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p11',
    name: 'Indus TV Unit',
    slug: 'indus-tv-unit',
    categoryId: 'cat-living-room',
    category: staticCategories[0],
    price: 62000,
    material: 'Sheesham Wood',
    stock: 9,
    isFeatured: false,
    isActive: true,
    tags: ['tv unit', 'sheesham', 'storage'],
    description: 'Solid sheesham wood TV unit with sliding doors and open shelves. Fits up to 75" TV.',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p12',
    name: 'Cloud Nine Mattress',
    slug: 'cloud-nine-mattress',
    categoryId: 'cat-bedroom',
    category: staticCategories[1],
    price: 45000,
    salePrice: 39000,
    material: 'Memory Foam',
    stock: 25,
    isFeatured: false,
    isActive: true,
    tags: ['mattress', 'memory foam', 'sleep'],
    description: '10-inch orthopedic memory foam mattress with cooling gel layer. King size.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p13',
    name: 'Tuscany Bookshelf',
    slug: 'tuscany-bookshelf',
    categoryId: 'cat-home-office',
    category: staticCategories[3],
    price: 42000,
    material: 'Solid Oak',
    stock: 11,
    isFeatured: false,
    isActive: true,
    tags: ['bookshelf', 'oak', 'storage'],
    description: '6-shelf solid oak bookcase with adjustable shelves and antique brass hardware.',
    images: [
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800',
      'https://images.unsplash.com/photo-1524758870432-af57e54afa26?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p14',
    name: 'Riviera Outdoor Lounger',
    slug: 'riviera-outdoor-lounger',
    categoryId: 'cat-outdoor',
    category: staticCategories[4],
    price: 32000,
    salePrice: 28000,
    material: 'Teak',
    stock: 8,
    isFeatured: false,
    isActive: true,
    tags: ['lounger', 'outdoor', 'pool'],
    description: 'Foldable teak sun lounger with adjustable backrest and thick weather-proof cushion.',
    images: [
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p15',
    name: 'Baroque Console Table',
    slug: 'baroque-console-table',
    categoryId: 'cat-living-room',
    category: staticCategories[0],
    price: 48000,
    material: 'Mango Wood & Glass',
    stock: 14,
    isFeatured: false,
    isActive: true,
    tags: ['console', 'entryway', 'glass'],
    description: 'Artisan-crafted console table with mango wood base and tempered glass shelf.',
    images: [
      'https://images.unsplash.com/photo-1582582621959-48d27397dc69?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p16',
    name: 'Luna Bedside Table',
    slug: 'luna-bedside-table',
    categoryId: 'cat-bedroom',
    category: staticCategories[1],
    price: 22000,
    salePrice: 19000,
    material: 'Acacia Wood',
    stock: 30,
    isFeatured: false,
    isActive: true,
    tags: ['nightstand', 'bedside', 'acacia'],
    description: 'Scandinavian-style bedside table with single drawer and open shelf. Sold as pair.',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p17',
    name: 'Horizon Sectional Sofa',
    slug: 'horizon-sectional-sofa',
    categoryId: 'cat-living-room',
    category: staticCategories[0],
    price: 320000,
    salePrice: 285000,
    material: 'Premium Fabric',
    stock: 3,
    isFeatured: true,
    isActive: true,
    tags: ['sectional', 'sofa', 'L-shape'],
    description: 'L-shaped 6-seater sectional sofa with chaise lounge in premium stain-resistant fabric.',
    images: [
      'https://images.unsplash.com/photo-1550254478-ead40cc54513?w=800',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p18',
    name: 'Marble Bistro Table',
    slug: 'marble-bistro-table',
    categoryId: 'cat-dining-room',
    category: staticCategories[2],
    price: 28000,
    material: 'Marble & Iron',
    stock: 16,
    isFeatured: false,
    isActive: true,
    tags: ['bistro', 'marble', 'small'],
    description: 'Compact 2-seater bistro table with Italian carrara marble top and black iron base.',
    images: [
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=800',
      'https://images.unsplash.com/photo-1581428982868-e410dd047a90?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p19',
    name: 'Sahara Floor Lamp',
    slug: 'sahara-floor-lamp',
    categoryId: 'cat-living-room',
    category: staticCategories[0],
    price: 15000,
    salePrice: 12500,
    material: 'Brass & Linen',
    stock: 22,
    isFeatured: false,
    isActive: true,
    tags: ['lamp', 'lighting', 'brass'],
    description: 'Adjustable arc floor lamp with antique brass finish and hand-stitched linen shade.',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p20',
    name: 'Vertex Standing Desk',
    slug: 'vertex-standing-desk',
    categoryId: 'cat-home-office',
    category: staticCategories[3],
    price: 85000,
    salePrice: 74000,
    material: 'Bamboo & Steel',
    stock: 7,
    isFeatured: false,
    isActive: true,
    tags: ['standing desk', 'ergonomic', 'bamboo'],
    description: 'Electric height-adjustable standing desk with bamboo top, dual motor, and memory presets.',
    images: [
      'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800',
      'https://images.unsplash.com/photo-1618220179428-22790b461013?w=800',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
